apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: live
spec:
  interval: 5m0s
  timeout: 2m0s
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: live
      version: ">=6.0.0 <7.0.0"
  releaseName: live
  targetNamespace: live
  values:
    service:
      type: ClusterIP
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
      valuesKey: values.yaml
