apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: infra
spec:
  interval: 10m
  releaseName: traefik
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: flux-system
  dependsOn:
    - name: kyverno
      namespace: infra
  values:
    providers:
      kubernetesCRD:
        enabled: false
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
    ingressClass:
      enabled: false
    gateway:
      enabled: false
    service:
      type: NodePort
    ports:
      web:
        nodePort: 30080
      websecure:
        nodePort: 30443
    metrics:
      prometheus:
        service:
          enabled: true
