apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    tag: ${TRAEFIK_VERSION}
